// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqqadhnckcglnzfhhynv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxcWFkaG5ja2NnbG56ZmhoeW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjgyMzAsImV4cCI6MjA2NjI0NDIzMH0.0Ocdf87F20GWCc-0odtiXx0D8KFcjMBgynWf3wOmneI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);